accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
ignore-dev-dependencies = true
private = { ignore = true }
