[package]
name = "rspdl-domain"
version.workspace = true
description = "Locale-independent semantic domain for RSPDL"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true

[dependencies]
num-bigint.workspace = true
num-prime.workspace = true
num-traits.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
