[package]
name = "rspdl-compiler"
version.workspace = true
description = "Compiler and execution facade for RSPDL"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true

[dependencies]
rspdl-domain = { path = "../rspdl-domain" }
rspdl-ko = { path = "../rspdl-ko" }
rspdl-solver-z3 = { path = "../rspdl-solver-z3" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
