use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::{Expr, Grammar, Rule};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CompileErrorKind {
    Syntax,
    DuplicateRule,
    UndefinedRule,
    UnknownMatcher,
    NullableRepetition,
    LeftRecursion,
    NoPublicRule,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompileError {
    pub kind: CompileErrorKind,
    pub offset: usize,
    pub message: String,
}

impl CompileError {
    fn new(kind: CompileErrorKind, offset: usize, message: impl Into<String>) -> Self {
        Self {
            kind,
            offset,
            message: message.into(),
        }
    }
}

impl std::fmt::Display for CompileError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "{} at byte {}", self.message, self.offset)
    }
}

impl std::error::Error for CompileError {}

#[derive(Clone, Debug)]
pub struct CompiledGrammar {
    grammar: Grammar,
    public_rules: Vec<String>,
    rules: Vec<Rule>,
}

impl CompiledGrammar {
    pub fn grammar(&self) -> &Grammar {
        &self.grammar
    }

    pub fn emit_rust(&self, function_name: &str) -> Result<String, CompileError> {
        if !is_rust_identifier(function_name) {
            return Err(CompileError::new(
                CompileErrorKind::Syntax,
                0,
                format!("{function_name:?} is not a Rust function identifier"),
            ));
        }
        let mut output = String::new();
        writeln!(
            output,
            "// @generated by rspdl-grammar-compiler. Do not edit."
        )
        .expect("writing to String cannot fail");
        writeln!(
            output,
            "pub(crate) fn {function_name}() -> ::rspdl_grammar_compiler::Grammar {{"
        )
        .expect("writing to String cannot fail");
        writeln!(
            output,
            "    ::rspdl_grammar_compiler::Grammar::from_generated_parts("
        )
        .expect("writing to String cannot fail");
        writeln!(output, "        vec![").expect("writing to String cannot fail");
        for name in &self.public_rules {
            writeln!(output, "            String::from({name:?}),")
                .expect("writing to String cannot fail");
        }
        writeln!(output, "        ],").expect("writing to String cannot fail");
        writeln!(output, "        vec![").expect("writing to String cannot fail");
        for rule in &self.rules {
            writeln!(
                output,
                "            ::rspdl_grammar_compiler::Rule::new({:?}, {}),",
                rule.name,
                emit_expression(&rule.expression)
            )
            .expect("writing to String cannot fail");
        }
        writeln!(output, "        ],").expect("writing to String cannot fail");
        writeln!(output, "    )").expect("writing to String cannot fail");
        writeln!(output, "}}").expect("writing to String cannot fail");
        Ok(output)
    }
}

#[derive(Clone, Debug, Default)]
pub struct GrammarCompiler {
    matchers: BTreeSet<String>,
}

impl GrammarCompiler {
    pub fn new(matchers: impl IntoIterator<Item = impl Into<String>>) -> Self {
        Self {
            matchers: matchers.into_iter().map(Into::into).collect(),
        }
    }

    pub fn compile(&self, source: &str) -> Result<CompiledGrammar, CompileError> {
        let tokens = Lexer::new(source).tokenize()?;
        let parsed = Parser::new(tokens).parse()?;
        validate(&parsed, &self.matchers)?;
        let public_rules = parsed
            .iter()
            .filter(|rule| rule.public)
            .map(|rule| rule.rule.name.clone())
            .collect::<Vec<_>>();
        let rules = parsed.into_iter().map(|rule| rule.rule).collect::<Vec<_>>();
        let grammar = Grammar::from_generated_parts(public_rules.clone(), rules.clone());
        Ok(CompiledGrammar {
            grammar,
            public_rules,
            rules,
        })
    }
}

fn emit_expression(expression: &Expr) -> String {
    match expression {
        Expr::Literal(value) => format!("::rspdl_grammar_compiler::Expr::literal({value:?})"),
        Expr::RuleRef(name) => format!("::rspdl_grammar_compiler::Expr::rule_ref({name:?})"),
        Expr::Matcher { name, arguments } => format!(
            "::rspdl_grammar_compiler::Expr::matcher({name:?}, vec![{}])",
            arguments
                .iter()
                .map(|argument| format!("String::from({argument:?})"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Expr::Sequence(expressions) => format!(
            "::rspdl_grammar_compiler::Expr::sequence(vec![{}])",
            expressions
                .iter()
                .map(emit_expression)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Expr::Choice(expressions) => format!(
            "::rspdl_grammar_compiler::Expr::choice(vec![{}])",
            expressions
                .iter()
                .map(emit_expression)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Expr::Optional(expression) => format!(
            "::rspdl_grammar_compiler::Expr::optional({})",
            emit_expression(expression)
        ),
        Expr::Repeat {
            expression,
            minimum,
        } => format!(
            "::rspdl_grammar_compiler::Expr::repeat({}, {minimum})",
            emit_expression(expression)
        ),
        Expr::Capture { name, expression } => format!(
            "::rspdl_grammar_compiler::Expr::capture({name:?}, {})",
            emit_expression(expression)
        ),
    }
}

fn is_rust_identifier(value: &str) -> bool {
    let mut characters = value.chars();
    characters
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
        && characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

#[derive(Clone, Debug)]
struct ParsedRule {
    public: bool,
    offset: usize,
    rule: Rule,
}

fn validate(rules: &[ParsedRule], matchers: &BTreeSet<String>) -> Result<(), CompileError> {
    if !rules.iter().any(|rule| rule.public) {
        return Err(CompileError::new(
            CompileErrorKind::NoPublicRule,
            0,
            "grammar must declare at least one public rule",
        ));
    }

    let mut definitions = BTreeMap::new();
    for rule in rules {
        if definitions.insert(rule.rule.name.clone(), rule).is_some() {
            return Err(CompileError::new(
                CompileErrorKind::DuplicateRule,
                rule.offset,
                format!("rule {:?} is defined more than once", rule.rule.name),
            ));
        }
    }

    for rule in rules {
        validate_references_and_matchers(
            &rule.rule.expression,
            rule.offset,
            &definitions,
            matchers,
        )?;
    }

    let nullable = nullable_rules(rules);
    for rule in rules {
        validate_repetition(&rule.rule.expression, rule.offset, &nullable)?;
    }
    validate_left_recursion(rules, &nullable)?;
    Ok(())
}

fn validate_references_and_matchers(
    expression: &Expr,
    offset: usize,
    rules: &BTreeMap<String, &ParsedRule>,
    matchers: &BTreeSet<String>,
) -> Result<(), CompileError> {
    match expression {
        Expr::RuleRef(name) if !rules.contains_key(name) => Err(CompileError::new(
            CompileErrorKind::UndefinedRule,
            offset,
            format!("rule {name:?} is not defined"),
        )),
        Expr::Matcher { name, .. } if !matchers.contains(name) => Err(CompileError::new(
            CompileErrorKind::UnknownMatcher,
            offset,
            format!("contextual matcher {name:?} is not registered"),
        )),
        Expr::Sequence(expressions) | Expr::Choice(expressions) => {
            for expression in expressions {
                validate_references_and_matchers(expression, offset, rules, matchers)?;
            }
            Ok(())
        }
        Expr::Optional(expression)
        | Expr::Repeat { expression, .. }
        | Expr::Capture { expression, .. } => {
            validate_references_and_matchers(expression, offset, rules, matchers)
        }
        Expr::Literal(_) | Expr::RuleRef(_) | Expr::Matcher { .. } => Ok(()),
    }
}

fn nullable_rules(rules: &[ParsedRule]) -> BTreeMap<String, bool> {
    let mut nullable = rules
        .iter()
        .map(|rule| (rule.rule.name.clone(), false))
        .collect::<BTreeMap<_, _>>();
    loop {
        let mut changed = false;
        for rule in rules {
            if !nullable[&rule.rule.name] && is_nullable(&rule.rule.expression, &nullable) {
                nullable.insert(rule.rule.name.clone(), true);
                changed = true;
            }
        }
        if !changed {
            return nullable;
        }
    }
}

fn is_nullable(expression: &Expr, nullable: &BTreeMap<String, bool>) -> bool {
    match expression {
        Expr::Literal(_) | Expr::Matcher { .. } => false,
        Expr::RuleRef(name) => nullable.get(name).copied().unwrap_or(false),
        Expr::Sequence(expressions) => expressions
            .iter()
            .all(|expression| is_nullable(expression, nullable)),
        Expr::Choice(expressions) => expressions
            .iter()
            .any(|expression| is_nullable(expression, nullable)),
        Expr::Optional(_) => true,
        Expr::Repeat {
            expression,
            minimum,
        } => *minimum == 0 || is_nullable(expression, nullable),
        Expr::Capture { expression, .. } => is_nullable(expression, nullable),
    }
}

fn validate_repetition(
    expression: &Expr,
    offset: usize,
    nullable: &BTreeMap<String, bool>,
) -> Result<(), CompileError> {
    match expression {
        Expr::Repeat { expression, .. } if is_nullable(expression, nullable) => {
            Err(CompileError::new(
                CompileErrorKind::NullableRepetition,
                offset,
                "a repeated expression must consume at least one token",
            ))
        }
        Expr::Sequence(expressions) | Expr::Choice(expressions) => {
            for expression in expressions {
                validate_repetition(expression, offset, nullable)?;
            }
            Ok(())
        }
        Expr::Optional(expression)
        | Expr::Repeat { expression, .. }
        | Expr::Capture { expression, .. } => validate_repetition(expression, offset, nullable),
        Expr::Literal(_) | Expr::RuleRef(_) | Expr::Matcher { .. } => Ok(()),
    }
}

fn validate_left_recursion(
    rules: &[ParsedRule],
    nullable: &BTreeMap<String, bool>,
) -> Result<(), CompileError> {
    let graph = rules
        .iter()
        .map(|rule| {
            let mut references = BTreeSet::new();
            first_rule_references(&rule.rule.expression, nullable, &mut references);
            (rule.rule.name.clone(), references)
        })
        .collect::<BTreeMap<_, _>>();
    for rule in rules {
        let mut visiting = BTreeSet::new();
        if reaches_rule(&rule.rule.name, &rule.rule.name, &graph, &mut visiting) {
            return Err(CompileError::new(
                CompileErrorKind::LeftRecursion,
                rule.offset,
                format!("rule {:?} is left recursive", rule.rule.name),
            ));
        }
    }
    Ok(())
}

fn first_rule_references(
    expression: &Expr,
    nullable: &BTreeMap<String, bool>,
    references: &mut BTreeSet<String>,
) {
    match expression {
        Expr::RuleRef(name) => {
            references.insert(name.clone());
        }
        Expr::Sequence(expressions) => {
            for expression in expressions {
                first_rule_references(expression, nullable, references);
                if !is_nullable(expression, nullable) {
                    break;
                }
            }
        }
        Expr::Choice(expressions) => {
            for expression in expressions {
                first_rule_references(expression, nullable, references);
            }
        }
        Expr::Optional(expression)
        | Expr::Repeat { expression, .. }
        | Expr::Capture { expression, .. } => {
            first_rule_references(expression, nullable, references);
        }
        Expr::Literal(_) | Expr::Matcher { .. } => {}
    }
}

fn reaches_rule(
    current: &str,
    target: &str,
    graph: &BTreeMap<String, BTreeSet<String>>,
    visiting: &mut BTreeSet<String>,
) -> bool {
    if !visiting.insert(current.to_owned()) {
        return false;
    }
    let reaches = graph.get(current).is_some_and(|next| {
        next.contains(target)
            || next
                .iter()
                .any(|name| reaches_rule(name, target, graph, visiting))
    });
    visiting.remove(current);
    reaches
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum TokenKind {
    Public,
    Identifier(String),
    String(String),
    At,
    Equals,
    Colon,
    Pipe,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Semicolon,
    Question,
    Star,
    Plus,
    Eof,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct Token {
    kind: TokenKind,
    offset: usize,
}

struct Lexer<'a> {
    source: &'a str,
    position: usize,
}

impl<'a> Lexer<'a> {
    fn new(source: &'a str) -> Self {
        Self {
            source,
            position: 0,
        }
    }

    fn tokenize(mut self) -> Result<Vec<Token>, CompileError> {
        let mut tokens = Vec::new();
        while self.position < self.source.len() {
            let character = self.current_character();
            if character.is_whitespace() {
                self.position += character.len_utf8();
                continue;
            }
            if character == '#' {
                while self.position < self.source.len() && self.current_character() != '\n' {
                    self.position += self.current_character().len_utf8();
                }
                continue;
            }
            let offset = self.position;
            let kind = match character {
                '@' => self.single(TokenKind::At),
                '=' => self.single(TokenKind::Equals),
                ':' => self.single(TokenKind::Colon),
                '|' => self.single(TokenKind::Pipe),
                '(' => self.single(TokenKind::LeftParen),
                ')' => self.single(TokenKind::RightParen),
                '[' => self.single(TokenKind::LeftBracket),
                ']' => self.single(TokenKind::RightBracket),
                '{' => self.single(TokenKind::LeftBrace),
                '}' => self.single(TokenKind::RightBrace),
                ',' => self.single(TokenKind::Comma),
                ';' => self.single(TokenKind::Semicolon),
                '?' => self.single(TokenKind::Question),
                '*' => self.single(TokenKind::Star),
                '+' => self.single(TokenKind::Plus),
                '"' => TokenKind::String(self.string_literal()?),
                _ if is_identifier_character(character) => self.identifier(),
                _ => {
                    return Err(CompileError::new(
                        CompileErrorKind::Syntax,
                        offset,
                        format!("unexpected grammar character {character:?}"),
                    ));
                }
            };
            tokens.push(Token { kind, offset });
        }
        tokens.push(Token {
            kind: TokenKind::Eof,
            offset: self.source.len(),
        });
        Ok(tokens)
    }

    fn current_character(&self) -> char {
        self.source[self.position..]
            .chars()
            .next()
            .expect("position is before source end")
    }

    fn single(&mut self, kind: TokenKind) -> TokenKind {
        self.position += 1;
        kind
    }

    fn identifier(&mut self) -> TokenKind {
        let start = self.position;
        while self.position < self.source.len() && is_identifier_character(self.current_character())
        {
            self.position += self.current_character().len_utf8();
        }
        match &self.source[start..self.position] {
            "pub" => TokenKind::Public,
            value => TokenKind::Identifier(value.to_owned()),
        }
    }

    fn string_literal(&mut self) -> Result<String, CompileError> {
        let start = self.position;
        self.position += 1;
        let mut output = String::new();
        while self.position < self.source.len() {
            let character = self.current_character();
            self.position += character.len_utf8();
            match character {
                '"' => return Ok(output),
                '\\' => {
                    if self.position >= self.source.len() {
                        break;
                    }
                    let escaped = self.current_character();
                    self.position += escaped.len_utf8();
                    output.push(match escaped {
                        '"' => '"',
                        '\\' => '\\',
                        'n' => '\n',
                        'r' => '\r',
                        't' => '\t',
                        _ => {
                            return Err(CompileError::new(
                                CompileErrorKind::Syntax,
                                self.position - escaped.len_utf8(),
                                format!("unsupported string escape \\{escaped}"),
                            ));
                        }
                    });
                }
                value => output.push(value),
            }
        }
        Err(CompileError::new(
            CompileErrorKind::Syntax,
            start,
            "unterminated string literal",
        ))
    }
}

fn is_identifier_character(character: char) -> bool {
    character == '_'
        || character == '-'
        || character.is_ascii_alphanumeric()
        || (!character.is_ascii() && !character.is_whitespace())
}

struct Parser {
    tokens: Vec<Token>,
    position: usize,
}

impl Parser {
    fn new(tokens: Vec<Token>) -> Self {
        Self {
            tokens,
            position: 0,
        }
    }

    fn parse(mut self) -> Result<Vec<ParsedRule>, CompileError> {
        let mut rules = Vec::new();
        while !matches!(self.current().kind, TokenKind::Eof) {
            rules.push(self.parse_rule()?);
        }
        if rules.is_empty() {
            return Err(self.error("grammar must contain at least one rule"));
        }
        Ok(rules)
    }

    fn parse_rule(&mut self) -> Result<ParsedRule, CompileError> {
        let public = self.consume_if(|kind| matches!(kind, TokenKind::Public));
        let offset = self.current().offset;
        let name = self.identifier("rule name")?;
        self.expect(|kind| matches!(kind, TokenKind::Equals), "=")?;
        let expression = self.parse_choice()?;
        self.expect(|kind| matches!(kind, TokenKind::Semicolon), ";")?;
        Ok(ParsedRule {
            public,
            offset,
            rule: Rule::new(name, expression),
        })
    }

    fn parse_choice(&mut self) -> Result<Expr, CompileError> {
        let mut alternatives = vec![self.parse_sequence()?];
        while self.consume_if(|kind| matches!(kind, TokenKind::Pipe)) {
            alternatives.push(self.parse_sequence()?);
        }
        Ok(if alternatives.len() == 1 {
            alternatives.pop().expect("one alternative")
        } else {
            Expr::choice(alternatives)
        })
    }

    fn parse_sequence(&mut self) -> Result<Expr, CompileError> {
        let mut expressions = Vec::new();
        while self.starts_primary() {
            expressions.push(self.parse_postfix()?);
            self.consume_if(|kind| matches!(kind, TokenKind::Comma));
        }
        if expressions.is_empty() {
            return Err(self.error("expected an expression"));
        }
        Ok(if expressions.len() == 1 {
            expressions.pop().expect("one expression")
        } else {
            Expr::sequence(expressions)
        })
    }

    fn parse_postfix(&mut self) -> Result<Expr, CompileError> {
        let mut expression = self.parse_primary()?;
        loop {
            expression = if self.consume_if(|kind| matches!(kind, TokenKind::Question)) {
                Expr::optional(expression)
            } else if self.consume_if(|kind| matches!(kind, TokenKind::Star)) {
                Expr::repeat(expression, 0)
            } else if self.consume_if(|kind| matches!(kind, TokenKind::Plus)) {
                Expr::repeat(expression, 1)
            } else {
                return Ok(expression);
            };
        }
    }

    fn parse_primary(&mut self) -> Result<Expr, CompileError> {
        if let TokenKind::Identifier(name) = &self.current().kind
            && matches!(
                self.tokens.get(self.position + 1).map(|token| &token.kind),
                Some(TokenKind::Colon)
            )
        {
            let name = name.clone();
            self.position += 2;
            return Ok(Expr::capture(name, self.parse_postfix()?));
        }
        match self.current().kind.clone() {
            TokenKind::Identifier(name) => {
                self.position += 1;
                Ok(Expr::rule_ref(name))
            }
            TokenKind::String(value) => {
                self.position += 1;
                Ok(Expr::literal(value))
            }
            TokenKind::At => self.parse_matcher(),
            TokenKind::LeftParen => {
                self.position += 1;
                let expression = self.parse_choice()?;
                self.expect(|kind| matches!(kind, TokenKind::RightParen), ")")?;
                Ok(expression)
            }
            TokenKind::LeftBracket => {
                self.position += 1;
                let expression = self.parse_choice()?;
                self.expect(|kind| matches!(kind, TokenKind::RightBracket), "]")?;
                Ok(Expr::optional(expression))
            }
            TokenKind::LeftBrace => {
                self.position += 1;
                let expression = self.parse_choice()?;
                self.expect(|kind| matches!(kind, TokenKind::RightBrace), "}")?;
                Ok(Expr::repeat(expression, 0))
            }
            _ => Err(self.error("expected a literal, rule, matcher, or group")),
        }
    }

    fn parse_matcher(&mut self) -> Result<Expr, CompileError> {
        self.position += 1;
        let name = self.identifier("matcher name")?;
        self.expect(|kind| matches!(kind, TokenKind::LeftParen), "(")?;
        let mut arguments = Vec::new();
        if !matches!(self.current().kind, TokenKind::RightParen) {
            loop {
                match self.current().kind.clone() {
                    TokenKind::String(value) => {
                        self.position += 1;
                        arguments.push(value);
                    }
                    _ => return Err(self.error("matcher arguments must be string literals")),
                }
                if !self.consume_if(|kind| matches!(kind, TokenKind::Comma)) {
                    break;
                }
            }
        }
        self.expect(|kind| matches!(kind, TokenKind::RightParen), ")")?;
        Ok(Expr::matcher(name, arguments))
    }

    fn starts_primary(&self) -> bool {
        matches!(
            self.current().kind,
            TokenKind::Identifier(_)
                | TokenKind::String(_)
                | TokenKind::At
                | TokenKind::LeftParen
                | TokenKind::LeftBracket
                | TokenKind::LeftBrace
        )
    }

    fn identifier(&mut self, description: &str) -> Result<String, CompileError> {
        match self.current().kind.clone() {
            TokenKind::Identifier(value) => {
                self.position += 1;
                Ok(value)
            }
            _ => Err(self.error(format!("expected {description}"))),
        }
    }

    fn expect(
        &mut self,
        predicate: impl FnOnce(&TokenKind) -> bool,
        expected: &str,
    ) -> Result<(), CompileError> {
        if predicate(&self.current().kind) {
            self.position += 1;
            Ok(())
        } else {
            Err(self.error(format!("expected {expected}")))
        }
    }

    fn consume_if(&mut self, predicate: impl FnOnce(&TokenKind) -> bool) -> bool {
        if predicate(&self.current().kind) {
            self.position += 1;
            true
        } else {
            false
        }
    }

    fn current(&self) -> &Token {
        &self.tokens[self.position]
    }

    fn error(&self, message: impl Into<String>) -> CompileError {
        CompileError::new(CompileErrorKind::Syntax, self.current().offset, message)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{InputAdapter, TerminalMatch};

    struct Words;

    impl InputAdapter<&str> for Words {
        fn match_literal(
            &self,
            tokens: &[&str],
            position: usize,
            literal: &str,
        ) -> Option<TerminalMatch> {
            (tokens.get(position).copied() == Some(literal))
                .then(|| TerminalMatch::new(position + 1, literal, position, position + 1))
        }

        fn match_contextual(
            &self,
            _tokens: &[&str],
            _position: usize,
            _matcher: &str,
            _arguments: &[String],
        ) -> Vec<TerminalMatch> {
            Vec::new()
        }
    }

    #[test]
    fn compiles_the_supported_ebnf_subset_and_emits_rust() {
        let source = r#"
            pub policy = role: @marked_ref("은", "는"), "수", effect: ("있다" | "없다");
        "#;
        let compiled = GrammarCompiler::new(["marked_ref"])
            .compile(source)
            .unwrap();
        assert_eq!(
            compiled.grammar().public_rules().collect::<Vec<_>>(),
            ["policy"]
        );
        let rust = compiled.emit_rust("policy_grammar").unwrap();
        assert!(rust.contains("fn policy_grammar()"));
        assert!(rust.contains("Expr::capture(\"effect\""));
    }

    #[test]
    fn compiled_optional_repetition_and_rule_references_execute() {
        let source = r#"
            pub entry = prefix ["b"] {item} suffix;
            prefix = "a";
            item = "c";
            suffix = "d";
        "#;
        let compiled = GrammarCompiler::default().compile(source).unwrap();
        for input in [
            vec!["a", "d"],
            vec!["a", "b", "d"],
            vec!["a", "c", "c", "d"],
            vec!["a", "b", "c", "d"],
        ] {
            compiled.grammar().parse("entry", &input, &Words).unwrap();
        }
        assert!(
            compiled
                .grammar()
                .parse("entry", &["a", "x", "d"], &Words)
                .is_err()
        );
    }

    #[test]
    fn rejects_malformed_and_duplicate_rules() {
        let compiler = GrammarCompiler::default();
        assert_eq!(
            compiler.compile("pub entry = \"a\"").unwrap_err().kind,
            CompileErrorKind::Syntax
        );
        assert_eq!(
            compiler
                .compile("pub entry = \"a\"; entry = \"b\";")
                .unwrap_err()
                .kind,
            CompileErrorKind::DuplicateRule
        );
    }

    #[test]
    fn rejects_undefined_rules_and_unknown_matchers() {
        assert_eq!(
            GrammarCompiler::default()
                .compile("pub entry = missing;")
                .unwrap_err()
                .kind,
            CompileErrorKind::UndefinedRule
        );
        assert_eq!(
            GrammarCompiler::default()
                .compile("pub entry = @locale();")
                .unwrap_err()
                .kind,
            CompileErrorKind::UnknownMatcher
        );
    }

    #[test]
    fn rejects_nullable_repetition_and_left_recursion() {
        assert_eq!(
            GrammarCompiler::default()
                .compile("pub entry = [\"a\"]*;")
                .unwrap_err()
                .kind,
            CompileErrorKind::NullableRepetition
        );
        assert_eq!(
            GrammarCompiler::default()
                .compile("pub entry = entry \"a\" | \"b\";")
                .unwrap_err()
                .kind,
            CompileErrorKind::LeftRecursion
        );
    }

    #[test]
    fn requires_a_public_entry_rule() {
        assert_eq!(
            GrammarCompiler::default()
                .compile("private = \"a\";")
                .unwrap_err()
                .kind,
            CompileErrorKind::NoPublicRule
        );
    }
}
